### ISSUE TITLE
[windows 系统] app.json 里的 pages 路径生成有误

### ISSUE THREAD

**Issue by bluefox1688** [meili/minui#1]
![qq 20171103105803](https://user-images.githubusercontent.com/11862797/32359112-2b1990f0-c086-11e7-85d2-b69af647f649.jpg)

在Clone后，使用`min dev`，app.json里的pages路径生成有误，如截图，什么也没调整过。
window 10开发环境，NPM版本为4.6.1，node版本为6.10.1

**Comment by min-team** [comment]
windows 下可能会存在一些问题，建议先用 mac 系统。windows 的问题会尽快查看。

**Comment by bluefox1688** [comment]
木有mac系统

**Comment by AbooJan** [comment]
在 mac 系统，用昨晚发布的那个版本1711020打开，一堆的错误

**Comment by min-team** [comment]
@AbooJan  基础库选过版本吗？

**Comment by min-team** [comment]
@AbooJan 

![](http://s3.mogucdn.com/mlcdn/c45406/171103_54iei7b9igchf0dl02la2lcd12c8a_2020x1544.png)

**Comment by AbooJan** [comment]
这个我选了，但是还是报错，不知道是不是 cli 构建的问题
```
WAService.js:3 jsEnginScriptError
Component is not found in path "pages/flex/@minui/wxc-example"
Error: Component is not found in path "pages/flex/@minui/wxc-example"
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:3940)
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:4063)
    at F (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:9977)
    at Object.t.addView (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:10942)
    at Function.value (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:956)
    at A (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:12156)
    at D (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:13238)
    at U (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:14541)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:17012)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:22046
errorReport @ WAService.js:3


Component is not found in path "pages/badge/@minui/wxc-example"
Error: Component is not found in path "pages/badge/@minui/wxc-example"
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:3940)
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:4063)
    at F (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:9977)
    at Object.t.addView (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:10942)
    at Function.value (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:956)
    at A (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:12156)
    at D (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:13238)
    at U (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:14541)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:17012)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:22046


Component is not found in path "pages/icon/@minui/wxc-example"
Error: Component is not found in path "pages/icon/@minui/wxc-example"
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:3940)
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:4063)
    at F (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:9977)
    at Object.t.addView (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:10942)
    at Function.value (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:956)
    at A (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:12156)
    at D (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:13238)
    at U (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:14541)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:17012)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:22046


Component is not found in path "pages/dialog/@minui/wxc-example"
Error: Component is not found in path "pages/dialog/@minui/wxc-example"
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:3940)
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:4063)
    at F (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:9977)
    at Object.t.addView (http://127.0.0.1:9973/appservice/__dev__/WAService.js:12:10942)
    at Function.value (http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:956)
    at A (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:12156)
    at D (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:13238)
    at U (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:14541)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:17012)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:13:22046
```

截图上传不了，一直卡，就直接拷贝错误信息了

**Comment by min-team** [comment]
@AbooJan  npm install  过吗？

**Comment by min-team** [comment]
@AbooJan 在 git clone 后，需要 run 一把 npm install 安装依赖。缺失的依赖在编译过程终会有诸如此类的报错，你看下是否属于同类问题？
![image](https://user-images.githubusercontent.com/32755767/32360561-08f8dece-c025-11e7-9aa0-5b902f3b78c4.png)

**Comment by AbooJan** [comment]
怪不得，没有npm install，以为min dev会自动执行😂

**Comment by arronf2e** [comment]
有没有发现，直接用小程序的自定义组件，在组件里写 <text>{{title}}</text>，调用的时候传title显示不出来，如果在{{title}}两边随便加点内容，就能显示出来，很奇怪

**Comment by bluefox1688** [comment]
@arronf2e 是有这个BUG，以下内容是官方发布的
暂未修复的已知bug
如果节点上有 wx:for 或 wx:if 属性，或者节点的父级是节点，则节点的 slot 属性会失效。
如果文本节点的绑定值是单纯的表达式 <view>{{xxx}}</view> ，则可能引发表达式更新错误，目前如遇这种情况，请在表达式后加一个空格来规避问题，如 <view>{{xxx}} </view>

**Comment by arronf2e** [comment]
@bluefox1688  OK，明白了

**Comment by Meowv** [comment]
windows 打开炸了，team 快修复呀！

**Comment by min-team** [comment]
@Meowv 看到，再等等

**Comment by min-team** [comment]
@Meowv @bluefox1688 windows系统的页面路径问题已修复，请更新 Min Cli 到1.0.2版本

**Comment by Meowv** [comment]
@min-team 太棒了，完美运行  💯👍👍👍
